### ISSUE TITLE
Issues using Breeze Starter Kit with Vue and Inertia

### ISSUE THREAD

**Issue by imakeinternet** [thedevdojo/auth#49]
### Description

When using the default Laravel Breeze starter kit with Vue and Inertia, the login and register links are opened in a modal window, which causes side effects. Specifically, login and registration redirects happen inside the opened modal window, leaving the original (non-authenticated) site behind the modal window. This is not the desired behavior and confuses users.

### Steps to Reproduce

1. From the homepage, click **Register**
2. Fill in the registration details
3. Click **Continue** to submit the registration
4. The modal window is redirected to the homepage (in logged-in status) with the original (non-authenticated) homepage behind the modal

The same issue occurs for the Login process:

1. From the homepage, click **Login**
2. Fill in the login details
3. Click **Continue** to login
4. The modal window is redirected to the homepage (in logged-in status) with the original (non-authenticated) homepage behind the modal

### Expected Behavior

After registering or logging in, the user should be redirected to the authenticated homepage without the original (non-authenticated) homepage remaining in the background.

### Actual Behavior

The modal window is redirected to the authenticated homepage while the original (non-authenticated) homepage remains in the background. This can be confusing, as the user sees the logged-in homepage within the modal and the non-authenticated homepage outside the modal.

### Possible Solution

Add full support for Inertia by returning proper Inertia responses when Inertia is used. Ensure that the authentication redirects respond with an Inertia response that displays the appropriate view/route in an Inertia environment.

### Environment

- Laravel Breeze starter kit with Vue and Inertia
- Browser: Chrome 125.0.6422.142

**Comment by everonegraham** [comment]
I'm having the [same issue](https://github.com/thedevdojo/auth/issues/48#issuecomment-2182993985).

**Comment by AlphaPhiri** [comment]
> I'm having the [same issue](https://github.com/thedevdojo/auth/issues/48#issuecomment-2182993985). I'm using Inertia + React with Breeze.

Am also having the same issue. Everythings is in Modals.

**Comment by tnylea** [comment]
Thanks for the detailed report. We'll be replicating and looking into a fix for this tomorrow. Currently the Blade stacks work fine with Breeze and Jetstream, but a few issues have been raised with the Inertia stacks that will be worked out very soon.

I'll respond in this thread when a release is being prepared 😉

**Comment by tnylea** [comment]
Ok, so it looks like this is due to Inertia utilizing the `Link` component in the `resources/js/Pages/Welcome.*` file.

You'll see this section in that file:

```html
<Link
    :href="route('login')"
    class="..."
>
    Log in
</Link>

<Link
    v-if="canRegister"
    :href="route('register')"
    class="..."
>
    Register
</Link>
```

These links need to be traditional `<a>` links as opposed to the `<Link>` element. Inertia will try to load these pages via XHR Requests, but we need them to function like normal requests, so you should replace those `Link` tags with `a` tags, like so:

```html
<a
    :href="route('login')"
    class="..."
>
    Log in
</a>

<a
    v-if="canRegister"
    :href="route('register')"
    class="..."
>
    Register
</a>
```

And then those page will function like normal.

I've also added this to the documentation here: https://devdojo.com/auth/docs/install/breeze/#modify-inertia-links

Let me know if that resolves your issue. Closing for now, but feel free to re-open if you think something else is not functioning correctly.

Appreciate you guys pointing this out.
